apiVersion: v1
kind: Service
metadata:
  name: {{ include "iris-widget.name" . }}
  labels: {{- include "iris-widget.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "iris-widget.name" . }}
